### ISSUE TITLE
500: window is not defined with @xstate/inspect

### ISSUE THREAD

**Issue by annaghi** [annaghi/xstate-svelte-workshop#1]
https://github.com/annaghi/xstate-svelte-workshop/blob/e60b85a882ea1f480b73c0bec140fb9a7c4f702a/src/workshop/complete/App.svelte#L10-L15

**Steps to reproduce**

1. Comment out the XState inspect related lines in `workshop/complete/App.svelte`
2. Check the app in the browser and allow browser popups -> statechart appears in another tab
3. Click on the Complete App -> it navigates to `/complete`
4. Refresh or reload the page

**Result of Step 4**
`500: window is not defined`

**Comment by Orion90** [comment]
This is because the code executes in SSR mode. You can solve it either by
```javascript
import {browser} from '$app/env'
if (browser) {
    inspect({
       iframe:false
    })
}
```
or using onMount() [which runs after the component is first rendered to the DOM](https://svelte.dev/tutorial/onmount)

```javascript
import { onMount } from 'svelte';
onMount(() => {
    inspect({
       iframe:false
    })
})
```

Hope this helps :)
